### ISSUE TITLE
Manhattan plot vs Study detail inconsistent

### ISSUE THREAD

**Issue by arthurkorte** [1001genomes/AraGWAS#100]
e.g 
https://aragwas.1001genomes.org/#/study/261

Permutation threshold is lower then Bonferroni (see Manhattan plot)
but we report more hits with Permutation (29) then Bonferroni (23)
Can you please check this ? to check

**Comment by mtog** [comment]
Thanks for pointing that out! It was because the manhattan plots data fetching script still had the MAF>0.05 encoded and computed a different Bonferroni threshold.
