### ISSUE TITLE
Gene-view - overlapping gene names

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#108]
rendering (hide gene names, maybe only show canonical form) when a lot of genes are present

**Comment by timeu** [comment]
Examples: 
- https://aragwas.1001genomes.org/#/gene/AT4G00650
- http://localhost:8080/#/gene/AT5G10140

**Comment by mtog** [comment]
A quick fix for this would be to only display the first isoform (which is the only one that has a description) for each gene. An alternative is to only show at most 5 isoforms on top of each other, but it becomes hard to choose which ones to display when you have overlapping genes...
What are your thoughts?
