### ISSUE TITLE
GWAS Hitmap: Link to GeneView

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#114]
Add link to geneView once an association is clicked

**Comment by mtog** [comment]
This is already implemented. It might not work for all points because we fetch the closest gene in a 4kb window, to ensure the clicked association is retrieved. Would you do it differently?

**Comment by timeu** [comment]
AH I didn't realize. No I think the solution is ok for now. We can close this then

**Comment by mtog** [comment]
Yes, this will be clearer once we add a small hovering information card.
