### ISSUE TITLE
Legend scales don't work if the page contains associations with the same score/maf

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#116]
The gene view always display the current visible page.
If the page only contains a broad peak where the associations have the same score or maf then the color scale won't work properly because there is no proper range.

Example: https://aragwas.1001genomes.org/#/gene/AT1G12210

**Comment by mtog** [comment]
@timeu please confirm my commit does what intended and close this.

**Comment by timeu** [comment]
Yes seems to work fine. I will close the issue
