### ISSUE TITLE
Elasticserach: make sure to filter by score and not pvalue

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#14]
Currently we index the pvalue field as a score and not a pvalue (7 vs 1e-07) but currently the queries filter using `lte` and the pvalue instead of `gte` and the score. 

We should change this in the queries. We can also consider to rename the field in ES from pvalue to score. We should do this before we index all studies

**Comment by mtog** [comment]
I'm fine for renaming it as it is the correct term for what the field contains. Should we put 'score' in the frontend as well?
