### ISSUE TITLE
Typo in API documentation for phenotypes

### ISSUE THREAD

**Issue by raf64flo** [1001genomes/AraGWAS#144]
Hi,

We've spotted with @HeleneRimbert  a typo in the documentation for Phenotypes [read](https://aragwas.1001genomes.org/docs/#phenotypes-read) and [studies](https://aragwas.1001genomes.org/docs/#phenotypes-studies). The doc is referencing `genotyping` instead of `phenotyping`, leading to no result when used: 

- read phenotype 624 is currently: https://aragwas.1001genomes.org/api/genotypes/624/ instead of https://aragwas.1001genomes.org/api/phenotypes/624/
- studies is currently : https://aragwas.1001genomes.org/api/genotypes/624/studies instead of https://aragwas.1001genomes.org/api/phenotypes/624/studies

**Comment by mtog** [comment]
Hi there,

Thank you for pointing this out and using our resource, we will correct it.
