### ISSUE TITLE
Top associations filtering

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#16]
The filtering does not seem to work. At least it doesn't change anything. 

Regarding the filter statements, we can take some ideas from GWA-Portal (https://github.com/timeu/GWA-Portal/blob/master/genophenbrowser-server/src/main/java/com/gmi/nordborglab/browser/server/service/impl/MetaAnalysisServiceImpl.java#L376)

**Comment by mtog** [comment]
We need to add aggregation as well.

**Comment by timeu** [comment]
yeah I can take a stab at it.

**Comment by mtog** [comment]
Aggregation done

**Comment by mtog** [comment]
Sorry, not for the % of snp displaying! Will do
