### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#17]
Please refer cosmetic issues here:
- phenotype detail view alignment
- study view layout

**Comment by mtog** [comment]
Add better layout to 'controls' switch in association list of phenotype and study detailed views.

**Comment by timeu** [comment]
regarding the controls switch which we display in the study and phenotype detail view. I think it would be nice if the table would take the entire available width, when the controls are hidden. On a large screen this might not make a big difference but on smaller screens it will make sure that the table is wide enough.

**Comment by timeu** [comment]
Also I would recommend to color only the pvalue column/cell in blue when it's significant. I think coloring the entire row is a bit redundant.

**Comment by mtog** [comment]
Yes for the blue, I didn't have that many in the top associations view in my local version. For the control I tried but I don't see a clean way of doing that with vuetify, any idea?
