### ISSUE TITLE
Properly implement paging

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#21]
Currently the paging for elasticsearch request is done via workaround (fetching 500 and then doing the paging). This should be done properly by passing paging information to the elastic functions

**Comment by mtog** [comment]
this is just to be able to use rest-framework paginator classes. Alternatively we could load all 300 results at once and do paging client-side with data-tables.

**Comment by timeu** [comment]
Yeah, I actually implemented a custom `ViewSet` and uses this for the ES searching: 
https://github.com/1001genomes/AraGWAS/blob/master/aragwas_server/gwasdb/rest.py#L254

With the new `v-data-table` we should probably switch from the `PaginNumberPaginator` to a `LimitOffsetPaginator` because it aligns better with how elasticserch does paging.
