### ISSUE TITLE
Implementing missing API endpoints

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#22]
retrieve,list, neighbouring snps and compute ld for SNPs: https://github.com/1001genomes/AraGWAS/blob/master/aragwas_server/gwasdb/rest.py#L265

list for genes: https://github.com/1001genomes/AraGWAS/blob/master/aragwas_server/gwasdb/rest.py#L236

top_assocations for phenotypes: https://github.com/1001genomes/AraGWAS/blob/master/aragwas_server/gwasdb/rest.py#L199

top_associations for studies:
https://github.com/1001genomes/AraGWAS/blob/master/aragwas_server/gwasdb/rest.py#L130

**Comment by mtog** [comment]
Is it worth having a gene list like for phenotypes/studies? The user can access any gene directly from the gene view so it might be a bit unnecessary.

**Comment by timeu** [comment]
yeah we might leave out the gene view. But then we need to remove the breadcrumb in the gene detail view because it points to /genes

**Comment by mtog** [comment]
Only miss 
retrieve,list, neighbouring snps and compute ld for SNPs
