### ISSUE TITLE
Navigating to page with a high number can cause the elasticsearch query to fail

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#26]
Elasticsearch has the issue that it has a limit for the from/size setting in the query (defualt: index.max_result_window: 10000). If the user navigates to a page that is beyond that window, the query will fail. There are a couple of solutions: 

1. Increase index.max_result_window:
2. Limit number of pages to max_result_window/page_size
3. Use the search_after functionality (see below)

Solution 1 is not recommended because the search will consume lots of memory and could crash ES
Solution 2 would be the easiest one but potentially not future proof if we get more and more associations (user can't navigate to significant ones which are further back in the list)
Solution 3 is probably the best one, however this means that the user can't jump to arbitrary page. It has to page through one by one (due to the technical implementation of the solution). 

Also if we implement grouping for the top-assocations than this might not be such as big problem because the page number will decrease. 

References:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

**Comment by mtog** [comment]
I think the third solution is good because a user will usually look page by page. But will users really go beyond page 400 in this case? Since the request is sent for every new set of filters he should be able to find his association of interest relatively quickly. We could implement better ordering of association and extend it to take into account gene_name (and phenotype).

**Comment by mtog** [comment]
Search_after will not work with the current queries well because we sort the associations by score and often many associations have the same score. We would need to add a second sorting on top of that to ensure we continue from the correct association.

**Comment by timeu** [comment]
yes it's in the documentation. we just need to add _uid as a second sort parameter.
