### ISSUE TITLE
Switching between study detail and manhattan plots sometimes fails

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#3]
Sometimes when clicking on the Manhattan tab or study details tab, the animation runs but, the tab content is not swapped

**Comment by mtog** [comment]
The content is only swapped when clicking inside the text div, I tried to put a wrapper to include as much margin as possible but it only worked horizontally. Any idea why?

Le 9 juin 2017 à 16:31, Ümit Seren <notifications@github.com<mailto:notifications@github.com>> a écrit :


Sometimes when clicking on the Manhattan tab or study details tab, the animation runs but, the tab content is not swapped

**Comment by timeu** [comment]
I am actually fixing this now and also update vuetify to the latest version
