### ISSUE TITLE
Similar phenotypes functionality

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#38]
There are 2. options: 

1. We add the ontology terms and their relationships to the database. This has to be done only once. Phenotypes from AraPheno already contain the ontology term, so we would just need to create the relationship when we import them. Additionally if we index the ontology term together with the top_assocations, we would calculate some statistics/aggregations on them and display them
2. We use AraPheno's REST endpoint to retrieve. similar phenotypes and check if they also exist in AraGWAS. Maybe we need to extend Arapheno's REST endpoint to support that use case. 

##### Advantages:
- Better performance
- No-coupling to AraPheno
- Statistics and filtering (top-associations)

##### Disadvantages:
- Information is displayed in two places (AraPheno, AraGWAS) --> might become out of sync
- Takes too much functionality of AraPheno
- Function to retrieve phenotypes from ontology and all sub-ontologies has to be re-implemented in AraGWAS

##### Advantages
- Almost no modification to existing model required 
- Information is always in sync with AraPheno
##### Disadvantages
 - Stronger coupling with AraPheno (if it goes down, the functionality is not available)
-  No statistics possible. Filtering possible but quite difficult.

I am leaning toward Solution 2, unless we can find a compelling reason to do solution 1.

**Comment by mtog** [comment]
Solution 2 is better since it won't require to update the aragwas database everytime someone submits a new phenotype on AraPheno. I don't think filtering is essential for the very basic usage we will do of that in araGWAS.

**Comment by timeu** [comment]
Well we would have to update the database when we import the phenotypes from Arapheno into AraGWAS and the ontology terms and their relationships are fixed (they only need to be imported once). So that wouldn't be a big issue. But I also think that solution 2 is easier and we should go with it. I leave the ticket open so that the others can also comment on it
