### ISSUE TITLE
Download functionalities

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#44]
- Download of Top Association List or Top Gene List
- Maybe in the future also download of all p-values per study
- Download of full database

**Comment by timeu** [comment]
Probably has to be implemented using a celery task and scroll and scan function of elasticseach.

**Comment by mtog** [comment]
- Full Data -> just elasticsearch content
- Individual Studies -> HDF5 files
- Top Associated Hits + Genes + Annotations -> With filters? In either case: celery task

**Comment by mtog** [comment]
We need to agree on which fields to add to the csv files. I would suggest:
For Genes:
- All genes information
For Associations:
- All association information
- Study name (without description, dates, etc)
- Phenotype name (without description, dates, etc)
- Genotype name (without description, dates, etc)
- Thresholds
- All SNP information

**Comment by dominikgrimm** [comment]
Sounds good. For Associations, also the effect estiamtes (e.g. betas, std of beta estimated etc.) if we have stored them

**Comment by mtog** [comment]
We haven't unfortunately
