### ISSUE TITLE
Add additional interactions to the genedetail view

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#57]
Following interactions should be added: 

- When the user hovers over a gene, all the associations that are located in the gene should be highlighted
- when the user navigates over a associations in the table, the corresponding association should be highlighted both in the manhattan plot as well as in the table.
- when the user navigates over an association in the manhattan plot, the corr. ass in the table should be highlighted.

**Comment by timeu** [comment]
Currently missing is the highlighting of the selected associations in the table. 
We need to discuss first how to do it from an UX point of view

**Comment by arthurkorte** [comment]
when the user navigates over an association in the manhattan plot ( and this is what many user will do) can we directly open a gene centric (or detailed) view from this ?

**Comment by mtog** [comment]
Yes, we will add that in the final version, the issue is that only the highly associated ones will have links to gene regions (since the others are not stored in the ES)
