### ISSUE TITLE
Currently only the associations from the first page of table are show in the Manhattan plot. Can we display all associations (maybe as additional option)?!

### ISSUE THREAD

**Issue by dominikgrimm** [1001genomes/AraGWAS#64]
Currently only the associations from the first page of table are show in the Manhattan plot. Can we display all associations (maybe as additional option)?!

**Comment by timeu** [comment]
It always displays the associations of the currently displayed page. So if you click on the next page, it will show you those associations. 
We were thinking of increasing the page size or maybe allowing the user to specify the page size.

**Comment by dominikgrimm** [comment]
Yes that would be good.
But still a check box with "Display all associations" would be cool. Because it will then nicely show the LD structure around this locus.
We also should add an Info Box that the Associations will be updated when one moves forward in the table..

**Comment by mtog** [comment]
We observed that displaying more than 100 associations becomes way too slow. We can add the option but it wouldn't be a pleasant experience for the user.

**Comment by mtog** [comment]
I close this issue because of the above-mentioned reason.
