### ISSUE TITLE
Permutation Based Thresholds for Results

### ISSUE THREAD

**Issue by dominikgrimm** [1001genomes/AraGWAS#72]

**Comment by arthurkorte** [comment]
Finished the permutations for the first trait
It looks actually really good:
https://aragwas.1001genomes.org/#/study/28
is an example of an highly inflated trait (binary trait, zero inflated) with 1690 hits after Bonferoni
Perm threshold is 10⁻22 , which 
reduced the number of significant associations to 15 !
Pretty neat example I think..., will continue on the other traits

**Comment by dominikgrimm** [comment]
Nice. That is a great example. Shall we use the Permutation based threshold as default then in all views? I think it would make sense, right?

**Comment by arthurkorte** [comment]
And most SNPs that are left over are on a region on Chr 1 containg the gene AT1G54160 with one NS substitution. This gene (NF-YA5) has been reported to be involved in drought, stress and light signalling, which makes a nice link to the Chlorosis Phenotype... Could be a really neat example to highlight the value of permutations...

**Comment by arthurkorte** [comment]
And @dominikgrimm : Yes, I think we should use it as default.
I hope I will finish all by mid August
(even thinking to try to adapt the script to use GPUs , that would make it way faster....)

**Comment by timeu** [comment]
How do you do the permutations ? Do you simply rotate the genotype and run the GWAS multiple times or is it using a different method ? I don't know if any of the GWAS models (LMM, etc) support GPUs yet.

**Comment by arthurkorte** [comment]
I rotate the phenotypes and re-run the GWAS, and yes there are GWAS methods for GPUs (e.g. https://www.ncbi.nlm.nih.gov/pubmed/26451813) I am just lacking the time to look into this.
So I guess for the moment brute force, but for the future GPU-based methods would be super-usefull for the permutations

**Comment by timeu** [comment]
Ok, alternativly we could use BoltLMM (http://www.nature.com/ng/journal/v47/n3/full/ng.3190.html) which is a magnitude faster than other LMM (FastLMM, etc), but I haven't tried it myself yet and I don't know how good it works with Arabidopsis data (it was developed for human data)

**Comment by mtog** [comment]
Closed this for now, we can add the more precise thresholds once all permutations have been computed.
