### ISSUE TITLE
study detail view should show statistics about impact, annotation, pvalue and maf

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#75]
Currently we display the statistics about snp type (genic vs non genic) and genes in the study detail view. 

The statistics for genes should be rather a bar chart (top 5) instead of a piechart
Additionally we could calculate statistics about impact, annotation, pvalue and maf and display them there also. 

We could keep the two tabs (genes, snps) and then display multiple charts for each type. 

For Genes: 

1.  top genes (bar-chart)
2.  GO terms ( piechart/barchart)

For SNPs:
1. genic vs non-genic (pie-chart)
2. impact (pie-chart)
3. annotation (piechart)
4. pvalue distribution (as histogram)
5. maf distribution (as histogram)

**Comment by dominikgrimm** [comment]
Great suggestions. They all make a lot of sense. 
Maybe a point 6. QQ-plots, genomic control?

**Comment by mtog** [comment]
We won't be able to aggregate over GO terms with the current ES structure. However, we can do a second lookup once we have the top genes if needed

**Comment by mtog** [comment]
Todo: make the manhattan plot vcard with a lower margin.

**Comment by timeu** [comment]
@mtog SNP impact Piechart appears twice and currently doesn't render anything.

**Comment by mtog** [comment]
Yup, and I still need to make the maf histogram more intelligible. I will do that properly when I come back from ISMB.
