### ISSUE TITLE
Graphical overview of genome wide associations

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#78]
We should create a graphical overview of all associations across the entire genome, bascially a 10 thousand meter view from above. 
There are couple of ways to do it. 

1. Chromosome view like in the [human GWAS catalog](https://www.ebi.ac.uk/gwas/diagram)
2. Zoomable Heatmap (see picture below) 

Alternatively we could have combination of the two above. Start with the chromosome view and if the user selects a chromosome switch to the heatmap view (for the entire chromosome) and then if the user zooms in further display the gene detail view. 

## Heatmap: 
5 chromosomes stacked horizontally
Each tick on the y-axis on the left is a GWAS study. The top 25 associations for each are plotted. The bar chart above shows how many associations are in the corresponding window/bin. 

![2017-07-13](https://user-images.githubusercontent.com/374296/28164344-5da6a298-67cf-11e7-9199-b1a1669cd87c.png)

**Comment by dominikgrimm** [comment]
That is awesome :) I think having both would be great. Maybe users could also switch between views providing a switch at the top of the plot to switch between chromosome vs heatmap illustration.
I like the ideas a lot :)

**Comment by dominikgrimm** [comment]
I think the heatmap is the best visualisation for researchers and follow up analysis. The chromosome view could be a good one for "advertisement" purposes.

**Comment by mtog** [comment]
I also like the heatmap a lot! Great idea 👍

**Comment by timeu** [comment]
JSON structure for overview: https://gist.github.com/timeu/e4d1bf0b726e43a80e12b5a279b51d14

**Comment by timeu** [comment]
![gwasheatmap](https://user-images.githubusercontent.com/374296/28629271-40c081aa-7227-11e7-83e3-f74cb0e35a1d.png)

**Comment by dominikgrimm** [comment]
@Ümit. Can we add a label to the x-axis, e.g. genomic position in Mbp or similar?!
Is it also possible to increase the size of the individual markers slightly, similar to the plot above? To increase readability in a screenshot.

**Comment by dominikgrimm** [comment]
@timeu @mtog  Currently the loading of the data for the heatmap takes quite some time. Can we add some text above the laoding bar that the laoding takes ~30 sec or similar?
We could also try to create a prefetched dump of the data that is needed for the heatmap. This might speed up data loading. What do you think?
Some of the experiment names are outside of the plotting frame.

**Comment by mtog** [comment]
First version for paper submission is live. I'll open a new issue for the possible enhancements.
