### ISSUE TITLE
Load_snps_by_region or load_snps_by_gene_id?

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#8]
When looking at snps near a gene should we load the snps within the gene boundaries or all snps associated with the gene (field: annotations.gene_name)

**Comment by timeu** [comment]
I already added a function load_snps_by_region which is used when loading a gene in the geneDetail component.

**Comment by mtog** [comment]
I saw that, but I had written the other one, the question is: do we want to include snps outside the gene region but known to be associated with it as well?

**Comment by timeu** [comment]
Currently `geneDetail.vue` will load all the SNPs for the loaded gene using the `load_snps_by_region` function. 
Actually we probably want to change this and load the associations in the specified region (mid point of gene + window size) together with the snps.

**Comment by mtog** [comment]
Yeah a larger window makes more sense, we can use the window size given by the zoom in geneDetail.
