### ISSUE TITLE
Interactions for Manhattan plots

### ISSUE THREAD

**Issue by timeu** [1001genomes/AraGWAS#81]
According to https://github.com/1001genomes/AraGWAS/issues/57#issuecomment-312245217

when the user navigates over an association in the manhattan plot ( and this is what many user will do) can we directly open a gene centric (or detailed) view from this ?

**Comment by mtog** [comment]
Not with the current data loading. In fact to make the plotting faster I just load an array of score/position/MAF values and not association objects. I'm afraid that querying the snp db (for non-significant hits) will be too slow.
What I can do is link to a search result page for that position on the gene tab. Or simply add a query once the snp is clicked
