### ISSUE TITLE
Graphical overview of GWAS improvements

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#83]
Continues from #78 for later improvements.
Ideas:
- zoomable regions

**Comment by mtog** [comment]
Need to add a histogram redraw functionality. Currently, when resizing window, new rect are added but the old one are not replaced (.exit().remove() is not working). 
This would also allow for loading from server json file instead of gist.

**Comment by mtog** [comment]
Add a slidebar legend to modify the score threshold to display (so as to sparsify or densify the map)

**Comment by mtog** [comment]
Add link to geneView once an association is clicked

**Comment by timeu** [comment]
Created separated issues and linked them to the [Project](https://github.com/1001genomes/AraGWAS/projects/2)
