### ISSUE TITLE
Re-index studies & associations with new thresholds

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#84]
Once the permutation file is available, the following command should be ran:
```
./manage.py compute_n_hits --maf 0 --update_all True --permutations /path/to/file
```
And:
```
./manage.py index_study --permutations /path/to/file
```
It is important to run the two commands in this order so that the permutation threshold is also stored in the es entries.
Of course, it is necessary to erase the previous aragwas and geno_* indeces from the ES to avoid duplicates and allow the newly created fields.

**Comment by mtog** [comment]
@timeu I tested this in my local configuration and it works. Could you reindex the studies on the server following the above instructions? Thanks!

**Comment by timeu** [comment]
I don't think we need to delete the geno_xx indices because they should not be affected by this change (correct me if I am wrong). I guess Arthur hasn't finished the permutations yet right?

**Comment by mtog** [comment]
He has, I just sent you the file.

**Comment by timeu** [comment]
@mtog: I re-indexed everything and deployed it to the live system. could you check and close the issue if it works.

**Comment by mtog** [comment]
Works fine!
