### ISSUE TITLE
New vuetify.js doesn't align properly

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#9]
AraGWASCatalog title in landing page is not centered for all display sizes.

**Comment by timeu** [comment]
Hmm I checked on aragwas.1001genomes.org, but I can't really reproduce it. Do you have a screenshot ?

**Comment by mtog** [comment]
![screen shot 2017-06-12 at 2 14 24 pm](https://user-images.githubusercontent.com/14583357/27033424-85a2df6e-4f79-11e7-93ac-fcf784424543.png)
It's nothing terrible but it seems that it places the text at discrete positions depending on the window size (try resizing your browser)
