### ISSUE TITLE
Add SNP annotation to download 

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#90]

**Comment by mtog** [comment]
Add overPermutation and overBonferroni fields too.

**Comment by mtog** [comment]
@dominikgrimm some associated SNPs have multiple annotations with up to 6 fields per annotations, should we limit the number of the ones we report in the downloadable files?

**Comment by dominikgrimm** [comment]
Mmh, you can concatenate them in a single string e.g. separated with a |
